# TCL File Generated by Component Editor 20.1
# Fri Aug 21 15:58:20 ICT 2026
# DO NOT MODIFY


# 
# sobel_soc "Sobel_SoC" v1.0
#  2026.08.21.15:58:20
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module sobel_soc
# 
set_module_property DESCRIPTION ""
set_module_property NAME sobel_soc
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME Sobel_SoC
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL sobel_soc_wrapper
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file sobel_soc_wrapper.sv SYSTEM_VERILOG PATH sobel_soc_wrapper.sv TOP_LEVEL_FILE


# 
# parameters
# 
add_parameter PARALLEL_PIXELS INTEGER 32
set_parameter_property PARALLEL_PIXELS DEFAULT_VALUE 32
set_parameter_property PARALLEL_PIXELS DISPLAY_NAME PARALLEL_PIXELS
set_parameter_property PARALLEL_PIXELS TYPE INTEGER
set_parameter_property PARALLEL_PIXELS UNITS None
set_parameter_property PARALLEL_PIXELS ALLOWED_RANGES -2147483648:2147483647
set_parameter_property PARALLEL_PIXELS HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point avalon_streaming_sink_0
# 
add_interface avalon_streaming_sink_0 avalon_streaming end
set_interface_property avalon_streaming_sink_0 associatedClock clock
set_interface_property avalon_streaming_sink_0 associatedReset reset_sink
set_interface_property avalon_streaming_sink_0 dataBitsPerSymbol 8
set_interface_property avalon_streaming_sink_0 errorDescriptor ""
set_interface_property avalon_streaming_sink_0 firstSymbolInHighOrderBits true
set_interface_property avalon_streaming_sink_0 maxChannel 0
set_interface_property avalon_streaming_sink_0 readyLatency 0
set_interface_property avalon_streaming_sink_0 ENABLED true
set_interface_property avalon_streaming_sink_0 EXPORT_OF ""
set_interface_property avalon_streaming_sink_0 PORT_NAME_MAP ""
set_interface_property avalon_streaming_sink_0 CMSIS_SVD_VARIABLES ""
set_interface_property avalon_streaming_sink_0 SVD_ADDRESS_GROUP ""

add_interface_port avalon_streaming_sink_0 asi_data data Input 256
add_interface_port avalon_streaming_sink_0 asi_valid valid Input 1
add_interface_port avalon_streaming_sink_0 asi_ready ready Output 1


# 
# connection point avalon_streaming_source_0
# 
add_interface avalon_streaming_source_0 avalon_streaming start
set_interface_property avalon_streaming_source_0 associatedClock clock
set_interface_property avalon_streaming_source_0 associatedReset reset_sink
set_interface_property avalon_streaming_source_0 dataBitsPerSymbol 8
set_interface_property avalon_streaming_source_0 errorDescriptor ""
set_interface_property avalon_streaming_source_0 firstSymbolInHighOrderBits true
set_interface_property avalon_streaming_source_0 maxChannel 0
set_interface_property avalon_streaming_source_0 readyLatency 0
set_interface_property avalon_streaming_source_0 ENABLED true
set_interface_property avalon_streaming_source_0 EXPORT_OF ""
set_interface_property avalon_streaming_source_0 PORT_NAME_MAP ""
set_interface_property avalon_streaming_source_0 CMSIS_SVD_VARIABLES ""
set_interface_property avalon_streaming_source_0 SVD_ADDRESS_GROUP ""

add_interface_port avalon_streaming_source_0 aso_data data Output 256
add_interface_port avalon_streaming_source_0 aso_valid valid Output 1
add_interface_port avalon_streaming_source_0 aso_ready ready Input 1


# 
# connection point reset_sink
# 
add_interface reset_sink reset end
set_interface_property reset_sink associatedClock clock
set_interface_property reset_sink synchronousEdges DEASSERT
set_interface_property reset_sink ENABLED true
set_interface_property reset_sink EXPORT_OF ""
set_interface_property reset_sink PORT_NAME_MAP ""
set_interface_property reset_sink CMSIS_SVD_VARIABLES ""
set_interface_property reset_sink SVD_ADDRESS_GROUP ""

add_interface_port reset_sink rst_n reset_n Input 1

