# TCL File Generated by Component Editor 20.1
# Fri Aug 21 14:29:58 ICT 2026
# DO NOT MODIFY


# 
# Write_Avalon_Sdr "Write_Avalon_Sdr" v1.0
#  2026.08.21.14:29:58
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module Write_Avalon_Sdr
# 
set_module_property DESCRIPTION ""
set_module_property NAME Write_Avalon_Sdr
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME Write_Avalon_Sdr
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL write_avalon_sdr
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file write_avalon_sdr.sv SYSTEM_VERILOG PATH write_avalon_sdr.sv TOP_LEVEL_FILE


# 
# parameters
# 
add_parameter OUTPUT_BASE_ADDR STD_LOGIC_VECTOR 822083584
set_parameter_property OUTPUT_BASE_ADDR DEFAULT_VALUE 822083584
set_parameter_property OUTPUT_BASE_ADDR DISPLAY_NAME OUTPUT_BASE_ADDR
set_parameter_property OUTPUT_BASE_ADDR TYPE STD_LOGIC_VECTOR
set_parameter_property OUTPUT_BASE_ADDR UNITS None
set_parameter_property OUTPUT_BASE_ADDR ALLOWED_RANGES 0:17179869183
set_parameter_property OUTPUT_BASE_ADDR HDL_PARAMETER true
add_parameter IMAGE_SIZE_BYTES INTEGER 307200
set_parameter_property IMAGE_SIZE_BYTES DEFAULT_VALUE 307200
set_parameter_property IMAGE_SIZE_BYTES DISPLAY_NAME IMAGE_SIZE_BYTES
set_parameter_property IMAGE_SIZE_BYTES TYPE INTEGER
set_parameter_property IMAGE_SIZE_BYTES UNITS None
set_parameter_property IMAGE_SIZE_BYTES ALLOWED_RANGES -2147483648:2147483647
set_parameter_property IMAGE_SIZE_BYTES HDL_PARAMETER true
add_parameter FIFO_DEPTH_LOG2 INTEGER 8
set_parameter_property FIFO_DEPTH_LOG2 DEFAULT_VALUE 8
set_parameter_property FIFO_DEPTH_LOG2 DISPLAY_NAME FIFO_DEPTH_LOG2
set_parameter_property FIFO_DEPTH_LOG2 TYPE INTEGER
set_parameter_property FIFO_DEPTH_LOG2 UNITS None
set_parameter_property FIFO_DEPTH_LOG2 ALLOWED_RANGES -2147483648:2147483647
set_parameter_property FIFO_DEPTH_LOG2 HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point m1
# 
add_interface m1 avalon start
set_interface_property m1 addressUnits SYMBOLS
set_interface_property m1 associatedClock clock
set_interface_property m1 associatedReset reset_sink
set_interface_property m1 bitsPerSymbol 8
set_interface_property m1 burstOnBurstBoundariesOnly false
set_interface_property m1 burstcountUnits WORDS
set_interface_property m1 doStreamReads false
set_interface_property m1 doStreamWrites false
set_interface_property m1 holdTime 0
set_interface_property m1 linewrapBursts false
set_interface_property m1 maximumPendingReadTransactions 0
set_interface_property m1 maximumPendingWriteTransactions 0
set_interface_property m1 readLatency 0
set_interface_property m1 readWaitTime 1
set_interface_property m1 setupTime 0
set_interface_property m1 timingUnits Cycles
set_interface_property m1 writeWaitTime 0
set_interface_property m1 ENABLED true
set_interface_property m1 EXPORT_OF ""
set_interface_property m1 PORT_NAME_MAP ""
set_interface_property m1 CMSIS_SVD_VARIABLES ""
set_interface_property m1 SVD_ADDRESS_GROUP ""

add_interface_port m1 avm_m1_address address Output 32
add_interface_port m1 avm_m1_write write Output 1
add_interface_port m1 avm_m1_writedata writedata Output 256
add_interface_port m1 avm_m1_byteenable byteenable Output 32
add_interface_port m1 avm_m1_burstcount burstcount Output 11
add_interface_port m1 avm_m1_waitrequest waitrequest Input 1


# 
# connection point reset_sink
# 
add_interface reset_sink reset end
set_interface_property reset_sink associatedClock clock
set_interface_property reset_sink synchronousEdges DEASSERT
set_interface_property reset_sink ENABLED true
set_interface_property reset_sink EXPORT_OF ""
set_interface_property reset_sink PORT_NAME_MAP ""
set_interface_property reset_sink CMSIS_SVD_VARIABLES ""
set_interface_property reset_sink SVD_ADDRESS_GROUP ""

add_interface_port reset_sink rst_n reset_n Input 1


# 
# connection point frame_done
# 
add_interface frame_done conduit end
set_interface_property frame_done associatedClock clock
set_interface_property frame_done associatedReset ""
set_interface_property frame_done ENABLED true
set_interface_property frame_done EXPORT_OF ""
set_interface_property frame_done PORT_NAME_MAP ""
set_interface_property frame_done CMSIS_SVD_VARIABLES ""
set_interface_property frame_done SVD_ADDRESS_GROUP ""

add_interface_port frame_done frame_done export Output 1


# 
# connection point sobel_data_in
# 
add_interface sobel_data_in conduit end
set_interface_property sobel_data_in associatedClock clock
set_interface_property sobel_data_in associatedReset ""
set_interface_property sobel_data_in ENABLED true
set_interface_property sobel_data_in EXPORT_OF ""
set_interface_property sobel_data_in PORT_NAME_MAP ""
set_interface_property sobel_data_in CMSIS_SVD_VARIABLES ""
set_interface_property sobel_data_in SVD_ADDRESS_GROUP ""

add_interface_port sobel_data_in data_in export Input 256


# 
# connection point sobel_valid_in
# 
add_interface sobel_valid_in conduit end
set_interface_property sobel_valid_in associatedClock clock
set_interface_property sobel_valid_in associatedReset ""
set_interface_property sobel_valid_in ENABLED true
set_interface_property sobel_valid_in EXPORT_OF ""
set_interface_property sobel_valid_in PORT_NAME_MAP ""
set_interface_property sobel_valid_in CMSIS_SVD_VARIABLES ""
set_interface_property sobel_valid_in SVD_ADDRESS_GROUP ""

add_interface_port sobel_valid_in valid_in export Input 1

