# TCL File Generated by Component Editor 20.1
# Wed Aug 05 15:44:17 ICT 2026
# DO NOT MODIFY


# 
# bnn_avl_wrapper "bnn_ip" v1.0
#  2026.08.05.15:44:17
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module bnn_avl_wrapper
# 
set_module_property DESCRIPTION ""
set_module_property NAME bnn_avl_wrapper
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME bnn_ip
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL bnn_avl_wrapper
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file bnn_avl_wrapper.sv SYSTEM_VERILOG PATH ip/bnn/quick_draw/bnn_avl_wrapper.sv TOP_LEVEL_FILE

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL bnn_avl_wrapper
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE true
add_fileset_file fc1_constants.sv SYSTEM_VERILOG PATH ip/bnn/quick_draw/fc1_constants.sv
add_fileset_file bdscnn_top.sv SYSTEM_VERILOG PATH ip/bnn/quick_draw/bdscnn_top.sv
add_fileset_file dw_pe.sv SYSTEM_VERILOG PATH ip/bnn/quick_draw/dw_pe.sv
add_fileset_file dw_top.sv SYSTEM_VERILOG PATH ip/bnn/quick_draw/dw_top.sv
add_fileset_file fc1_folded_neuron.sv SYSTEM_VERILOG PATH ip/bnn/quick_draw/fc1_folded_neuron.sv
add_fileset_file fc1_folded_top.sv SYSTEM_VERILOG PATH ip/bnn/quick_draw/fc1_folded_top.sv
add_fileset_file fc1_folded_top_test.sv SYSTEM_VERILOG PATH ip/bnn/quick_draw/fc1_folded_top_test.sv
add_fileset_file fc1_neuron.sv SYSTEM_VERILOG PATH ip/bnn/quick_draw/fc1_neuron.sv
add_fileset_file fc1_top.sv SYSTEM_VERILOG PATH ip/bnn/quick_draw/fc1_top.sv
add_fileset_file fc2_top.sv SYSTEM_VERILOG PATH ip/bnn/quick_draw/fc2_top.sv
add_fileset_file mcp_pe.sv SYSTEM_VERILOG PATH ip/bnn/quick_draw/mcp_pe.sv
add_fileset_file mcp_top.sv SYSTEM_VERILOG PATH ip/bnn/quick_draw/mcp_top.sv
add_fileset_file popcount.sv SYSTEM_VERILOG PATH ip/bnn/quick_draw/popcount.sv
add_fileset_file window3x3s1.sv SYSTEM_VERILOG PATH ip/bnn/quick_draw/window3x3s1.sv
add_fileset_file window4x4s2.sv SYSTEM_VERILOG PATH ip/bnn/quick_draw/window4x4s2.sv
add_fileset_file pw_top.sv SYSTEM_VERILOG PATH ip/bnn/quick_draw/pw_top.sv
add_fileset_file pw_pe.sv SYSTEM_VERILOG PATH ip/bnn/quick_draw/pw_pe.sv
add_fileset_file bnn_avl_wrapper.sv SYSTEM_VERILOG PATH ip/bnn/quick_draw/bnn_avl_wrapper.sv


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point avl_mm
# 
add_interface avl_mm avalon end
set_interface_property avl_mm addressUnits WORDS
set_interface_property avl_mm associatedClock clock
set_interface_property avl_mm associatedReset reset_sink
set_interface_property avl_mm bitsPerSymbol 8
set_interface_property avl_mm burstOnBurstBoundariesOnly false
set_interface_property avl_mm burstcountUnits WORDS
set_interface_property avl_mm explicitAddressSpan 0
set_interface_property avl_mm holdTime 0
set_interface_property avl_mm linewrapBursts false
set_interface_property avl_mm maximumPendingReadTransactions 0
set_interface_property avl_mm maximumPendingWriteTransactions 0
set_interface_property avl_mm readLatency 0
set_interface_property avl_mm readWaitTime 1
set_interface_property avl_mm setupTime 0
set_interface_property avl_mm timingUnits Cycles
set_interface_property avl_mm writeWaitTime 0
set_interface_property avl_mm ENABLED true
set_interface_property avl_mm EXPORT_OF ""
set_interface_property avl_mm PORT_NAME_MAP ""
set_interface_property avl_mm CMSIS_SVD_VARIABLES ""
set_interface_property avl_mm SVD_ADDRESS_GROUP ""

add_interface_port avl_mm avl_mm_address address Input 3
add_interface_port avl_mm avl_mm_read read Input 1
add_interface_port avl_mm avl_mm_readdata readdata Output 32
add_interface_port avl_mm avl_mm_write write Input 1
add_interface_port avl_mm avl_mm_writedata writedata Input 32
set_interface_assignment avl_mm embeddedsw.configuration.isFlash 0
set_interface_assignment avl_mm embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avl_mm embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avl_mm embeddedsw.configuration.isPrintableDevice 0


# 
# connection point reset_sink
# 
add_interface reset_sink reset end
set_interface_property reset_sink associatedClock clock
set_interface_property reset_sink synchronousEdges DEASSERT
set_interface_property reset_sink ENABLED true
set_interface_property reset_sink EXPORT_OF ""
set_interface_property reset_sink PORT_NAME_MAP ""
set_interface_property reset_sink CMSIS_SVD_VARIABLES ""
set_interface_property reset_sink SVD_ADDRESS_GROUP ""

add_interface_port reset_sink rst_n reset_n Input 1


# 
# connection point avalon_streaming_sink
# 
add_interface avalon_streaming_sink avalon_streaming end
set_interface_property avalon_streaming_sink associatedClock clock
set_interface_property avalon_streaming_sink associatedReset reset_sink
set_interface_property avalon_streaming_sink dataBitsPerSymbol 8
set_interface_property avalon_streaming_sink errorDescriptor ""
set_interface_property avalon_streaming_sink firstSymbolInHighOrderBits true
set_interface_property avalon_streaming_sink maxChannel 0
set_interface_property avalon_streaming_sink readyLatency 0
set_interface_property avalon_streaming_sink ENABLED true
set_interface_property avalon_streaming_sink EXPORT_OF ""
set_interface_property avalon_streaming_sink PORT_NAME_MAP ""
set_interface_property avalon_streaming_sink CMSIS_SVD_VARIABLES ""
set_interface_property avalon_streaming_sink SVD_ADDRESS_GROUP ""

add_interface_port avalon_streaming_sink avl_s_data data Input 32
add_interface_port avalon_streaming_sink avl_s_valid valid Input 1
add_interface_port avalon_streaming_sink avl_s_ready ready Output 1

