#ifndef _ALTERA_HPS_0_H_
#define _ALTERA_HPS_0_H_

/*
 * This file was automatically generated by the swinfo2header utility.
 * 
 * Created from SOPC Builder system 'soc_system' in
 * file '../../soc_system.sopcinfo'.
 */

/*
 * This file contains macros for module 'hps_0' and devices
 * connected to the following master:
 *   h2f_axi_master
 * 
 * Do not include this header file and another header file created for a
 * different module or master group at the same time.
 * Doing so may result in duplicate macro names.
 * Instead, use the system header file which has macros with unique names.
 */

/*
 * Macros for device 'avalon_control_0', class 'avalon_control'
 * The macros are prefixed with 'AVALON_CONTROL_0_'.
 * The prefix is the slave descriptor.
 */
#define AVALON_CONTROL_0_COMPONENT_TYPE avalon_control
#define AVALON_CONTROL_0_COMPONENT_NAME avalon_control_0
#define AVALON_CONTROL_0_BASE 0x0
#define AVALON_CONTROL_0_SPAN 4
#define AVALON_CONTROL_0_END 0x3


#endif /* _ALTERA_HPS_0_H_ */
