# ============================================================
# Timing constraints for current DE10_NANO top-level
# ============================================================

# Board input clock: FPGA_CLK1_50 = 50 MHz
create_clock -name FPGA_CLK1_50 -period 20.000 [get_ports {FPGA_CLK1_50}]

# Derive clocks generated by PLLs, including the HDMI 25 MHz clock
derive_pll_clocks
derive_clock_uncertainty

# Mechanical switches/keys are asynchronous debug/reset inputs.
# Synchronizers/debouncing should be used for functional signals.
set_false_path -from [get_ports {SW[*]}]
set_false_path -from [get_ports {KEY[*]}]

# LED outputs are only used for human-visible debug.
set_false_path -to [get_ports {LED[*]}]
