//=======================================================
//  This code is generated by Terasic System Builder
//  Modified: add buffer_AI + bdscnn_top
//=======================================================

module DE10_NANO(

    //////////// CLOCK //////////
    input                       FPGA_CLK1_50,
    input                       FPGA_CLK2_50,
    input                       FPGA_CLK3_50,

    //////////// HDMI //////////
    inout                       HDMI_I2C_SCL,
    inout                       HDMI_I2C_SDA,
    inout                       HDMI_I2S,
    inout                       HDMI_LRCLK,
    inout                       HDMI_MCLK,
    inout                       HDMI_SCLK,
    output                      HDMI_TX_CLK,
    output                      HDMI_TX_DE,
    output          [23:0]      HDMI_TX_D,
    output                      HDMI_TX_HS,
    input                       HDMI_TX_INT,
    output                      HDMI_TX_VS,

    //////////// HPS //////////
    inout                       HPS_CONV_USB_N,
    output          [14:0]      HPS_DDR3_ADDR,
    output           [2:0]      HPS_DDR3_BA,
    output                      HPS_DDR3_CAS_N,
    output                      HPS_DDR3_CKE,
    output                      HPS_DDR3_CK_N,
    output                      HPS_DDR3_CK_P,
    output                      HPS_DDR3_CS_N,
    output           [3:0]      HPS_DDR3_DM,
    inout           [31:0]      HPS_DDR3_DQ,
    inout            [3:0]      HPS_DDR3_DQS_N,
    inout            [3:0]      HPS_DDR3_DQS_P,
    output                      HPS_DDR3_ODT,
    output                      HPS_DDR3_RAS_N,
    output                      HPS_DDR3_RESET_N,
    input                       HPS_DDR3_RZQ,
    output                      HPS_DDR3_WE_N,
    output                      HPS_ENET_GTX_CLK,
    inout                       HPS_ENET_INT_N,
    output                      HPS_ENET_MDC,
    inout                       HPS_ENET_MDIO,
    input                       HPS_ENET_RX_CLK,
    input            [3:0]      HPS_ENET_RX_DATA,
    input                       HPS_ENET_RX_DV,
    output           [3:0]      HPS_ENET_TX_DATA,
    output                      HPS_ENET_TX_EN,
    inout                       HPS_GSENSOR_INT,
    inout                       HPS_I2C0_SCLK,
    inout                       HPS_I2C0_SDAT,
    inout                       HPS_I2C1_SCLK,
    inout                       HPS_I2C1_SDAT,
    inout                       HPS_KEY,
    inout                       HPS_LED,
    inout                       HPS_LTC_GPIO,
    output                      HPS_SD_CLK,
    inout                       HPS_SD_CMD,
    inout            [3:0]      HPS_SD_DATA,
    output                      HPS_SPIM_CLK,
    input                       HPS_SPIM_MISO,
    output                      HPS_SPIM_MOSI,
    inout                       HPS_SPIM_SS,
    input                       HPS_UART_RX,
    output                      HPS_UART_TX,
    input                       HPS_USB_CLKOUT,
    inout            [7:0]      HPS_USB_DATA,
    input                       HPS_USB_DIR,
    input                       HPS_USB_NXT,
    output                      HPS_USB_STP,

    //////////// KEY //////////
    input            [1:0]      KEY,

    //////////// LED //////////
    output           [7:0]      LED,

    //////////// SW //////////
    input            [3:0]      SW,

    //////////// GPIO_0 //////////
    inout           [35:0]      GPIO_0
);


//=======================================================
//  REG/WIRE declarations
//=======================================================

    wire clock50;
    assign clock50 = FPGA_CLK1_50;

    wire reset_n;
    assign reset_n = SW[0];

    // =====================================================
    // SOC
    // =====================================================
    wire         hps_fpga_reset_n;
    wire         soc_connect;
    wire [255:0] soc_read_data;
    wire         soc_read_done;
    wire         soc_read_enable;
    wire         soc_read_reset;

    // =====================================================
    // AVALON / FRAME BUFFERS
    // =====================================================
    wire avl_write_done;
    wire ai_buffer_done;

    // =====================================================
    // AI STREAM
    // buffer_AI -> bdscnn_top
    // =====================================================
    wire       ai_core_rst_n;
    wire       ai_img_valid;
    wire       ai_img_data;
    wire       ai_busy;
    wire       ai_stream_done;

    // bdscnn_top result
    wire       ai_sys_valid;
    wire [3:0] ai_class_out;

    // Kết quả AI đã được chốt để HPS đọc qua PIO Input 32-bit
    wire [31:0] ai_result_word;

    // Giữ toàn bộ class 4 bit để hiển thị đủ 10 class (0..9)
    logic [3:0] ai_class_led;

    // Các cờ debug được giữ lại để mắt thường quan sát được
    logic seen_ai_stream_done;
    logic seen_ai_sys_valid;

    // =====================================================
    // HDMI
    // =====================================================
    wire        clock;
    wire        lock;
    wire        txdone;
    wire        start;
    wire [23:0] datatx;

    wire hdmi_data;
    wire hdmi_enable;
    wire hdmi_reset;

    wire hdmi_CLK;
    assign HDMI_TX_CLK = hdmi_CLK;

    wire hdmi_config;

    wire hdmi_SDA_rx;
    wire hdmi_SDA_sel;
    wire hdmi_SDA_tx;

    assign HDMI_I2C_SDA = hdmi_SDA_sel ? 1'bz : hdmi_SDA_tx;
    assign hdmi_SDA_rx  = HDMI_I2C_SDA;

    wire hdmi_SCL;
    assign HDMI_I2C_SCL = hdmi_SCL;

    wire hdmi_DE;
    assign HDMI_TX_DE = hdmi_DE;

    wire [23:0] hdmi_DATA;
    assign HDMI_TX_D = hdmi_DATA;

    wire hdmi_HSYNC;
    assign HDMI_TX_HS = hdmi_HSYNC;

    wire hdmi_VSYNC;
    assign HDMI_TX_VS = hdmi_VSYNC;


    // =====================================================
    // LED DEBUG CHO AI
    // =====================================================
    //
    // LED[3:0] : class AI đầy đủ, dạng nhị phân
    // LED[4]   : đã nhận được sys_valid từ bdscnn_top
    // LED[5]   : buffer_AI đã phát đủ 1024 pixel
    // LED[6]   : buffer_AI đã nhận đủ 4 beat Avalon
    // LED[7]   : AI đang bận xử lý
    //
    // Ví dụ:
    //   class 0  -> LED[3:0] = 0000
    //   class 4  -> LED[3:0] = 0100
    //   class 8  -> LED[3:0] = 1000
    //   class 9  -> LED[3:0] = 1001
    // =====================================================
    assign LED[3:0] = ai_class_led;
    assign LED[4]   = seen_ai_sys_valid;
    assign LED[5]   = seen_ai_stream_done;
    assign LED[6]   = ai_buffer_done;
    assign LED[7]   = ai_busy;

    // Chốt class và các pulse debug để LED giữ sáng.
    always_ff @(posedge clock50 or negedge reset_n) begin
        if (!reset_n) begin
            ai_class_led        <= 4'b0000;
            seen_ai_stream_done <= 1'b0;
            seen_ai_sys_valid   <= 1'b0;
        end else begin
            // Khi bắt đầu đọc frame mới, xóa trạng thái cũ.
            if (soc_read_reset) begin
                ai_class_led        <= 4'b0000;
                seen_ai_stream_done <= 1'b0;
                seen_ai_sys_valid   <= 1'b0;
            end

            // Buffer đã phát đủ 1024 pixel vào bdscnn_top.
            if (ai_stream_done) begin
                seen_ai_stream_done <= 1'b1;
            end

            // Kết quả class chỉ được chốt khi sys_valid hợp lệ.
            if (ai_sys_valid) begin
                ai_class_led      <= ai_class_out;
                seen_ai_sys_valid <= 1'b1;
            end
        end
    end


//=======================================================
//  Structural coding
//=======================================================

    // =====================================================
    // SOC SYSTEM
    // =====================================================
    soc_system u0 (
        // Output
        .ext_connect_o_export       (soc_connect), // trigger from CPU, send to pio_out 
        .read_data_o_export         (soc_read_data),
        .read_done_o_export         (soc_read_done),
        .read_enable_o_export       (soc_read_enable),
        .read_reset_o_export        (soc_read_reset),
        .read_start_i_export        (soc_connect), // start trigger for DMA to start 

        // FPGA -> HPS: PIO Input 32-bit tại offset 0x10
        .ai_result_i_export         (ai_result_word),

        // Clock & Reset
        .clk_clk                    (clock50),
        .reset_reset_n              (hps_fpga_reset_n),

        // HPS DDR3
        .memory_mem_a               (HPS_DDR3_ADDR),
        .memory_mem_ba              (HPS_DDR3_BA),
        .memory_mem_ck              (HPS_DDR3_CK_P),
        .memory_mem_ck_n            (HPS_DDR3_CK_N),
        .memory_mem_cke             (HPS_DDR3_CKE),
        .memory_mem_cs_n            (HPS_DDR3_CS_N),
        .memory_mem_ras_n           (HPS_DDR3_RAS_N),
        .memory_mem_cas_n           (HPS_DDR3_CAS_N),
        .memory_mem_we_n            (HPS_DDR3_WE_N),
        .memory_mem_reset_n         (HPS_DDR3_RESET_N),
        .memory_mem_dq              (HPS_DDR3_DQ),
        .memory_mem_dqs             (HPS_DDR3_DQS_P),
        .memory_mem_dqs_n           (HPS_DDR3_DQS_N),
        .memory_mem_odt             (HPS_DDR3_ODT),
        .memory_mem_dm              (HPS_DDR3_DM),
        .memory_oct_rzqin           (HPS_DDR3_RZQ),
        .hps_0_h2f_reset_reset_n    (hps_fpga_reset_n)
    );


    // =====================================================
    // HDMI FRAME BUFFER
    // =====================================================
    buffer_hdmi buffer_soc_hdmi (
        .rstn_i         (reset_n),

        // AVALON
        .avl_clk_i      (clock50),
        .avl_reset_i    (soc_read_reset),
        .avl_data_i     (soc_read_data),
        .avl_enable_i   (soc_read_enable),
        .avl_done_o     (avl_write_done),

        // HDMI
        .hdmi_clk_i     (hdmi_CLK),
        .hdmi_reset_i   (hdmi_reset),
        .hdmi_enable_i  (hdmi_enable),
        .hdmi_data_o    (hdmi_data)
    );


    // =====================================================
    // AI FRAME BUFFER
    // =====================================================
    buffer_AI buffer_soc_ai (
        .rstn_i             (reset_n),

        // AVALON WRITE
        .avl_clk_i          (clock50),
        .avl_reset_i        (soc_read_reset),
        .avl_data_i         (soc_read_data),
        .avl_enable_i       (soc_read_enable),
        .avl_done_o         (ai_buffer_done),

        // AI STREAM
        .ai_clk_i           (clock50),
        .ai_result_valid_i  (ai_sys_valid),
        .ai_rst_n_o         (ai_core_rst_n),
        .img_valid_o        (ai_img_valid),
        .img_data_o         (ai_img_data),
        .ai_busy_o          (ai_busy),
        .ai_stream_done_o   (ai_stream_done)
    );


    // =====================================================
    // BDSCNN TOP
    // Input nối trực tiếp từ output của buffer_AI.
    // =====================================================
    bdscnn_top u_bdscnn_top (
        .clk        (clock50),
        .rst_n      (ai_core_rst_n),

        .img_valid  (ai_img_valid),
        .img_data   (ai_img_data),

        .sys_valid  (ai_sys_valid),
        .class_out  (ai_class_out)
    );


    // =====================================================
    // AI RESULT REGISTER
    //
    // Chốt class tại cạnh lên của ai_sys_valid.
    // HPS đọc ai_result_word thông qua PIO Input 32-bit:
    //   bit 31    : result valid đã chốt
    //   bit 30    : AI busy
    //   bit 29    : stream done
    //   bit 28    : AI buffer done
    //   bit 23:16 : result sequence
    //   bit 3:0   : class index
    // =====================================================
    ai_result_register u_ai_result_register (
        .clk_i           (clock50),
        .rstn_i          (reset_n),

        // Bắt đầu frame mới thì xóa cờ valid cũ
        .new_frame_i     (soc_read_reset),

        // Kết quả từ bdscnn_top
        .result_valid_i  (ai_sys_valid),
        .class_i         (ai_class_out),

        // Trạng thái debug
        .ai_busy_i       (ai_busy),
        .stream_done_i   (ai_stream_done),
        .buffer_done_i   (ai_buffer_done),

        // Sang PIO Input 32-bit của soc_system
        .result_word_o   (ai_result_word)
    );


    // =====================================================
    // HDMI PIXEL CLOCK
    // =====================================================
    pll_49Mhz pll (
        .refclk     (clock50),
        .rst        (!reset_n),
        .outclk_0   (hdmi_CLK),
        .locked     (lock)
    );


    // =====================================================
    // HDMI I2C CONFIG
    // =====================================================
    hdmi_i2c_config i2c_config (
        .clk_i       (clock50),
        .rst_i       (reset_n),
        .ena_i       (lock),
        .i2c_done_i  (txdone),
        .i2c_start_o (start),
        .i2c_data_o  (datatx),
        .mem_done_o  (hdmi_config)
    );


    // =====================================================
    // I2C TRANSMITTER
    // =====================================================
    i2ctx tx (
        .clk_i       (clock50),
        .rst_i       (reset_n),
        .start_i     (start),
        .datatx_i    (datatx),
        .datarx_i    (hdmi_SDA_rx),
        .sda_sel_o   (hdmi_SDA_sel),
        .txdone_o    (txdone),
        .sda_o       (hdmi_SDA_tx),
        .scl_o       (hdmi_SCL)
    );


    // =====================================================
    // VGA / HDMI TIMING
    // =====================================================
    vga_hdmi vga_hdmi (
        .clk_i        (hdmi_CLK),
        .rst_i        (reset_n),
        .hdmi_data_i  (hdmi_data),
        .rst_frame_o  (hdmi_reset),
        .hdmi_ena_o   (hdmi_enable),
        .hsync_o      (hdmi_HSYNC),
        .vsync_o      (hdmi_VSYNC),
        .data_ena_o   (hdmi_DE),
        .hdmi_data_o  (hdmi_DATA)
    );

endmodule
