# TCL File Generated by Component Editor 19.1
# Fri Jan 09 16:00:47 ICT 2026
# DO NOT MODIFY


# 
# avalon_control "avalon_control" v1.0
#  2026.01.09.16:00:47
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module avalon_control
# 
set_module_property DESCRIPTION ""
set_module_property NAME avalon_control
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME avalon_control
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL avalon_control
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file avalon_control.sv SYSTEM_VERILOG PATH ip/ddr3/avalon_control.sv


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point s0
# 
add_interface s0 avalon end
set_interface_property s0 addressUnits WORDS
set_interface_property s0 associatedClock clock
set_interface_property s0 associatedReset reset
set_interface_property s0 bitsPerSymbol 8
set_interface_property s0 burstOnBurstBoundariesOnly false
set_interface_property s0 burstcountUnits WORDS
set_interface_property s0 explicitAddressSpan 0
set_interface_property s0 holdTime 0
set_interface_property s0 linewrapBursts false
set_interface_property s0 maximumPendingReadTransactions 0
set_interface_property s0 maximumPendingWriteTransactions 0
set_interface_property s0 readLatency 0
set_interface_property s0 readWaitTime 1
set_interface_property s0 setupTime 0
set_interface_property s0 timingUnits Cycles
set_interface_property s0 writeWaitTime 0
set_interface_property s0 ENABLED true
set_interface_property s0 EXPORT_OF ""
set_interface_property s0 PORT_NAME_MAP ""
set_interface_property s0 CMSIS_SVD_VARIABLES ""
set_interface_property s0 SVD_ADDRESS_GROUP ""

add_interface_port s0 avs_s0_writedata writedata Input 32
add_interface_port s0 avs_s0_write write Input 1
set_interface_assignment s0 embeddedsw.configuration.isFlash 0
set_interface_assignment s0 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment s0 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment s0 embeddedsw.configuration.isPrintableDevice 0


# 
# connection point do_read
# 
add_interface do_read conduit end
set_interface_property do_read associatedClock clock
set_interface_property do_read associatedReset reset
set_interface_property do_read ENABLED true
set_interface_property do_read EXPORT_OF ""
set_interface_property do_read PORT_NAME_MAP ""
set_interface_property do_read CMSIS_SVD_VARIABLES ""
set_interface_property do_read SVD_ADDRESS_GROUP ""

add_interface_port do_read do_read export Output 1


# 
# connection point burst_length
# 
add_interface burst_length conduit end
set_interface_property burst_length associatedClock clock
set_interface_property burst_length associatedReset reset
set_interface_property burst_length ENABLED true
set_interface_property burst_length EXPORT_OF ""
set_interface_property burst_length PORT_NAME_MAP ""
set_interface_property burst_length CMSIS_SVD_VARIABLES ""
set_interface_property burst_length SVD_ADDRESS_GROUP ""

add_interface_port burst_length burst_length export Output 11


# 
# connection point init_addr
# 
add_interface init_addr conduit end
set_interface_property init_addr associatedClock clock
set_interface_property init_addr associatedReset reset
set_interface_property init_addr ENABLED true
set_interface_property init_addr EXPORT_OF ""
set_interface_property init_addr PORT_NAME_MAP ""
set_interface_property init_addr CMSIS_SVD_VARIABLES ""
set_interface_property init_addr SVD_ADDRESS_GROUP ""

add_interface_port init_addr init_addr export Output 20

