# TCL File Generated by Component Editor 19.1
# Fri Jan 09 16:00:14 ICT 2026
# DO NOT MODIFY


# 
# avalon_sdr "avalon_sdr" v1.0
#  2026.01.09.16:00:14
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module avalon_sdr
# 
set_module_property DESCRIPTION ""
set_module_property NAME avalon_sdr
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME avalon_sdr
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL avalon_sdr
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file avalon_sdr.sv SYSTEM_VERILOG PATH ip/ddr3/avalon_sdr.sv


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point m0
# 
add_interface m0 avalon start
set_interface_property m0 addressUnits SYMBOLS
set_interface_property m0 associatedClock clock
set_interface_property m0 associatedReset reset
set_interface_property m0 bitsPerSymbol 8
set_interface_property m0 burstOnBurstBoundariesOnly false
set_interface_property m0 burstcountUnits WORDS
set_interface_property m0 doStreamReads false
set_interface_property m0 doStreamWrites false
set_interface_property m0 holdTime 0
set_interface_property m0 linewrapBursts false
set_interface_property m0 maximumPendingReadTransactions 0
set_interface_property m0 maximumPendingWriteTransactions 0
set_interface_property m0 readLatency 0
set_interface_property m0 readWaitTime 1
set_interface_property m0 setupTime 0
set_interface_property m0 timingUnits Cycles
set_interface_property m0 writeWaitTime 0
set_interface_property m0 ENABLED true
set_interface_property m0 EXPORT_OF ""
set_interface_property m0 PORT_NAME_MAP ""
set_interface_property m0 CMSIS_SVD_VARIABLES ""
set_interface_property m0 SVD_ADDRESS_GROUP ""

add_interface_port m0 avm_m0_read read Output 1
add_interface_port m0 avm_m0_address address Output 32
add_interface_port m0 avm_m0_readdata readdata Input 32
add_interface_port m0 avm_m0_readdatavalid readdatavalid Input 1
add_interface_port m0 avm_m0_byteenable byteenable Output 4
add_interface_port m0 avm_m0_waitrequest waitrequest Input 1
add_interface_port m0 avm_m0_burstcount burstcount Output 11


# 
# connection point do_read
# 
add_interface do_read conduit end
set_interface_property do_read associatedClock clock
set_interface_property do_read associatedReset reset
set_interface_property do_read ENABLED true
set_interface_property do_read EXPORT_OF ""
set_interface_property do_read PORT_NAME_MAP ""
set_interface_property do_read CMSIS_SVD_VARIABLES ""
set_interface_property do_read SVD_ADDRESS_GROUP ""

add_interface_port do_read do_read export Input 1


# 
# connection point out_data_1
# 
add_interface out_data_1 conduit end
set_interface_property out_data_1 associatedClock clock
set_interface_property out_data_1 associatedReset reset
set_interface_property out_data_1 ENABLED true
set_interface_property out_data_1 EXPORT_OF ""
set_interface_property out_data_1 PORT_NAME_MAP ""
set_interface_property out_data_1 CMSIS_SVD_VARIABLES ""
set_interface_property out_data_1 SVD_ADDRESS_GROUP ""

add_interface_port out_data_1 out_data_1 export Output 32


# 
# connection point out_data_2
# 
add_interface out_data_2 conduit end
set_interface_property out_data_2 associatedClock clock
set_interface_property out_data_2 associatedReset reset
set_interface_property out_data_2 ENABLED true
set_interface_property out_data_2 EXPORT_OF ""
set_interface_property out_data_2 PORT_NAME_MAP ""
set_interface_property out_data_2 CMSIS_SVD_VARIABLES ""
set_interface_property out_data_2 SVD_ADDRESS_GROUP ""

add_interface_port out_data_2 out_data_2 export Output 32


# 
# connection point init_addr
# 
add_interface init_addr conduit end
set_interface_property init_addr associatedClock clock
set_interface_property init_addr associatedReset reset
set_interface_property init_addr ENABLED true
set_interface_property init_addr EXPORT_OF ""
set_interface_property init_addr PORT_NAME_MAP ""
set_interface_property init_addr CMSIS_SVD_VARIABLES ""
set_interface_property init_addr SVD_ADDRESS_GROUP ""

add_interface_port init_addr init_addr export Input 20


# 
# connection point burst_length
# 
add_interface burst_length conduit end
set_interface_property burst_length associatedClock clock
set_interface_property burst_length associatedReset reset
set_interface_property burst_length ENABLED true
set_interface_property burst_length EXPORT_OF ""
set_interface_property burst_length PORT_NAME_MAP ""
set_interface_property burst_length CMSIS_SVD_VARIABLES ""
set_interface_property burst_length SVD_ADDRESS_GROUP ""

add_interface_port burst_length burst_length export Input 11

