#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <fcntl.h>
#include <sys/mman.h>
#include <stdint.h>
#include <inttypes.h>
#include <errno.h>

// Include file header được sinh ra từ Qsys
#ifndef _ALTERA_HPS_0_H_
#define _ALTERA_HPS_0_H_

/*
 * This file was automatically generated by the swinfo2header utility.
 * 
 * Created from SOPC Builder system 'soc_system' in
 * file 'soc_system.sopcinfo'.
 */

/*
 * This file contains macros for module 'hps_0' and devices
 * connected to the following masters:
 *   h2f_axi_master
 *   h2f_lw_axi_master
 * 
 * Do not include this header file and another header file created for a
 * different module or master group at the same time.
 * Doing so may result in duplicate macro names.
 * Instead, use the system header file which has macros with unique names.
 */

/*
 * Macros for device 'pio64_out_1', class 'pio64_out'
 * The macros are prefixed with 'PIO64_OUT_1_'.
 * The prefix is the slave descriptor.
 */
#define PIO64_OUT_1_COMPONENT_TYPE pio64_out
#define PIO64_OUT_1_COMPONENT_NAME pio64_out_1
#define PIO64_OUT_1_BASE 0x0
#define PIO64_OUT_1_SPAN 8
#define PIO64_OUT_1_END 0x7

/*
 * Macros for device 'pio64_out_0', class 'pio64_out'
 * The macros are prefixed with 'PIO64_OUT_0_'.
 * The prefix is the slave descriptor.
 */
#define PIO64_OUT_0_COMPONENT_TYPE pio64_out
#define PIO64_OUT_0_COMPONENT_NAME pio64_out_0
#define PIO64_OUT_0_BASE 0x8
#define PIO64_OUT_0_SPAN 8
#define PIO64_OUT_0_END 0xf

/*
 * Macros for device 'pio64_in_0', class 'pio64_in'
 * The macros are prefixed with 'PIO64_IN_0_'.
 * The prefix is the slave descriptor.
 */
#define PIO64_IN_0_COMPONENT_TYPE pio64_in
#define PIO64_IN_0_COMPONENT_NAME pio64_in_0
#define PIO64_IN_0_BASE 0x10
#define PIO64_IN_0_SPAN 8
#define PIO64_IN_0_END 0x17

/*
 * Macros for device 'sysid_qsys', class 'altera_avalon_sysid_qsys'
 * The macros are prefixed with 'SYSID_QSYS_'.
 * The prefix is the slave descriptor.
 */
#define SYSID_QSYS_COMPONENT_TYPE altera_avalon_sysid_qsys
#define SYSID_QSYS_COMPONENT_NAME sysid_qsys
#define SYSID_QSYS_BASE 0x1000
#define SYSID_QSYS_SPAN 8
#define SYSID_QSYS_END 0x1007
#define SYSID_QSYS_ID 2899645186
#define SYSID_QSYS_TIMESTAMP 1766564740

/*
 * Macros for device 'jtag_uart', class 'altera_avalon_jtag_uart'
 * The macros are prefixed with 'JTAG_UART_'.
 * The prefix is the slave descriptor.
 */
#define JTAG_UART_COMPONENT_TYPE altera_avalon_jtag_uart
#define JTAG_UART_COMPONENT_NAME jtag_uart
#define JTAG_UART_BASE 0x2000
#define JTAG_UART_SPAN 8
#define JTAG_UART_END 0x2007
#define JTAG_UART_IRQ 2
#define JTAG_UART_READ_DEPTH 64
#define JTAG_UART_READ_THRESHOLD 8
#define JTAG_UART_WRITE_DEPTH 64
#define JTAG_UART_WRITE_THRESHOLD 8

/*
 * Macros for device 'dipsw_pio', class 'altera_avalon_pio'
 * The macros are prefixed with 'DIPSW_PIO_'.
 * The prefix is the slave descriptor.
 */
#define DIPSW_PIO_COMPONENT_TYPE altera_avalon_pio
#define DIPSW_PIO_COMPONENT_NAME dipsw_pio
#define DIPSW_PIO_BASE 0x4000
#define DIPSW_PIO_SPAN 16
#define DIPSW_PIO_END 0x400f
#define DIPSW_PIO_IRQ 0
#define DIPSW_PIO_BIT_CLEARING_EDGE_REGISTER 1
#define DIPSW_PIO_BIT_MODIFYING_OUTPUT_REGISTER 0
#define DIPSW_PIO_CAPTURE 1
#define DIPSW_PIO_DATA_WIDTH 4
#define DIPSW_PIO_DO_TEST_BENCH_WIRING 0
#define DIPSW_PIO_DRIVEN_SIM_VALUE 0
#define DIPSW_PIO_EDGE_TYPE ANY
#define DIPSW_PIO_FREQ 50000000
#define DIPSW_PIO_HAS_IN 1
#define DIPSW_PIO_HAS_OUT 0
#define DIPSW_PIO_HAS_TRI 0
#define DIPSW_PIO_IRQ_TYPE EDGE
#define DIPSW_PIO_RESET_VALUE 0

/*
 * Macros for device 'button_pio', class 'altera_avalon_pio'
 * The macros are prefixed with 'BUTTON_PIO_'.
 * The prefix is the slave descriptor.
 */
#define BUTTON_PIO_COMPONENT_TYPE altera_avalon_pio
#define BUTTON_PIO_COMPONENT_NAME button_pio
#define BUTTON_PIO_BASE 0x5000
#define BUTTON_PIO_SPAN 16
#define BUTTON_PIO_END 0x500f
#define BUTTON_PIO_IRQ 1
#define BUTTON_PIO_BIT_CLEARING_EDGE_REGISTER 1
#define BUTTON_PIO_BIT_MODIFYING_OUTPUT_REGISTER 0
#define BUTTON_PIO_CAPTURE 1
#define BUTTON_PIO_DATA_WIDTH 2
#define BUTTON_PIO_DO_TEST_BENCH_WIRING 0
#define BUTTON_PIO_DRIVEN_SIM_VALUE 0
#define BUTTON_PIO_EDGE_TYPE FALLING
#define BUTTON_PIO_FREQ 50000000
#define BUTTON_PIO_HAS_IN 1
#define BUTTON_PIO_HAS_OUT 0
#define BUTTON_PIO_HAS_TRI 0
#define BUTTON_PIO_IRQ_TYPE EDGE
#define BUTTON_PIO_RESET_VALUE 0

/*
 * Macros for device 'ILC', class 'interrupt_latency_counter'
 * The macros are prefixed with 'ILC_'.
 * The prefix is the slave descriptor.
 */
#define ILC_COMPONENT_TYPE interrupt_latency_counter
#define ILC_COMPONENT_NAME ILC
#define ILC_BASE 0x30000
#define ILC_SPAN 256
#define ILC_END 0x300ff


#endif /* _ALTERA_HPS_0_H_ */

// Địa chỉ vật lý của cầu HPS-to-FPGA (Heavyweight Bridge)
#define H2F_BRIDGE_BASE 0xC0000000

// Kích thước vùng nhớ cần ánh xạ. 
// PIO cuối cùng (PIO64_IN_0) kết thúc ở 0x17. 
// Ta lấy 0x20 (32 bytes) hoặc 4096 (Page size) cho an toàn.
#define H2F_BRIDGE_SPAN 0x1000 

int main(int argc, char **argv) {
    int fd;
    void *virtual_base;
    
    // Khai báo các con trỏ trỏ tới thanh ghi phần cứng
    // Sử dụng 'volatile' để báo cho trình biên dịch biết giá trị có thể thay đổi ngoài ý muốn (do phần cứng)
    volatile uint64_t *pio_a_ptr = NULL;
    volatile uint64_t *pio_b_ptr = NULL;
    volatile uint64_t *pio_sum_ptr = NULL;

    uint64_t num_a = 0;
    uint64_t num_b = 0;
    uint64_t sum = 0;

    // 1. Kiểm tra tham số đầu vào
    if (argc != 3) {
        printf("Usage: %s <number_a> <number_b>\n", argv[0]);
        return -1;
    }

    // Chuyển đổi chuỗi sang số 64-bit
    num_a = strtoull(argv[1], NULL, 10);
    num_b = strtoull(argv[2], NULL, 10);

    // 2. Mở file /dev/mem để truy cập bộ nhớ vật lý
    // O_SYNC là bắt buộc để đảm bảo ghi/đọc trực tiếp xuống phần cứng không qua Cache
    fd = open("/dev/mem", O_RDWR | O_SYNC);
    if (fd < 0) {
        perror("ERROR: Could not open /dev/mem");
        return -1;
    }

    // 3. Ánh xạ địa chỉ vật lý sang địa chỉ ảo (User Space)
    virtual_base = mmap(NULL, H2F_BRIDGE_SPAN, PROT_READ | PROT_WRITE, MAP_SHARED, fd, H2F_BRIDGE_BASE);
    
    if (virtual_base == MAP_FAILED) {
        perror("ERROR: mmap() failed");
        close(fd);
        return -1;
    }

    // 4. Tính toán địa chỉ ảo cho từng thanh ghi dựa trên Macro trong hps_0.h
    // Lưu ý: Phải ép kiểu về (uint8_t *) trước khi cộng offset để tính đúng theo byte
    
    // PIO64_OUT_1 (Base 0x0) -> Đóng vai trò số A
    pio_a_ptr = (uint64_t *)((uint8_t *)virtual_base + PIO64_OUT_1_BASE);
    
    // PIO64_OUT_0 (Base 0x8) -> Đóng vai trò số B
    pio_b_ptr = (uint64_t *)((uint8_t *)virtual_base + PIO64_OUT_0_BASE);
    
    // PIO64_IN_0 (Base 0x10) -> Đóng vai trò Tổng (Sum)
    pio_sum_ptr = (uint64_t *)((uint8_t *)virtual_base + PIO64_IN_0_BASE);

    // 5. Thực hiện Ghi và Đọc phần cứng
    printf("Hardware Adder Interface:\n");
    printf("Writing A = %" PRIu64 " to Offset 0x%X\n", num_a, PIO64_OUT_1_BASE);
    printf("Writing B = %" PRIu64 " to Offset 0x%X\n", num_b, PIO64_OUT_0_BASE);

    *pio_a_ptr = num_a; // Ghi xuống FPGA
    *pio_b_ptr = num_b; // Ghi xuống FPGA

    // Đọc kết quả từ FPGA
    sum = *pio_sum_ptr;

    printf("Result read from Offset 0x%X: Sum = %" PRIu64 "\n", PIO64_IN_0_BASE, sum);

    // 6. Dọn dẹp và thoát
    if (munmap(virtual_base, H2F_BRIDGE_SPAN) != 0) {
        perror("ERROR: munmap() failed");
        close(fd);
        return -1;
    }

    close(fd);
    return 0;
}
